[tool.black]
line-length = 100
target-version = ['py312']
exclude = '''
/(
    .venv
  | venv
  | alembic
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = ["alembic", "migrations"]
